---
# Example job that users can submit to the kueue system
# Apply this with: kubectl apply -f example-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
  namespace: kueue-user
  labels:
    kueue.x-k8s.io/queue-name: user-queue
spec:
  parallelism: 1
  completions: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: worker
          image: busybox:1.35
          command:
            - /bin/sh
            - -c
          args:
            - |
              echo "Job started at $(date)"
              echo "Running workload simulation..."
              for i in $(seq 1 10); do
                echo "Processing step $i/10"
                sleep 2
              done
              echo "Job completed at $(date)"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
