apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: team-kubeconfig-role
rules:
# Allow creating and managing jobs for queue submission
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete"]
# Allow viewing pods to check job status
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
# Allow viewing pod logs for debugging
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
# Allow viewing kueue workloads
- apiGroups: ["kueue.x-k8s.io"]
  resources: ["workloads"]
  verbs: ["get", "list", "watch"]
# Allow viewing events for troubleshooting
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]