---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nvidia-gpu-operator
  namespace: nvidia-gpu-operator
spec:
  interval: 10m
  url: https://helm.ngc.nvidia.com/nvidia
  type: default
